#  menu items
[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[main]]
  name = "Guides"
  weight = 2
  url = "guides/"

[[main]]
  name = "About"
  weight = 3
  url = "about/about"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"